### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by flotwig** [doowb/npm-api-dependents#5]
Trying to run this example from the docs:

```js
var npm = require('npm-api')();
var dependents = require('npm-api-dependents');
npm.use(dependents());

var repo = npm.repo('micromatch');

// returns a readable stream
repo.dependents()
  .on('data', function(repo) {
    console.log(repo);
  });
```

Gives me this: 

```
TypeError: Class constructor NpmApi cannot be invoked without 'new'
```

Node 8.9.3 and 12.4.0.

**Comment by doowb** [comment]
NPM made some changes to their api and I updated `npm-api`, but I haven't gotten to this library to update it yet.

`npm-api` exports a class so will need to use the `new` keyword:

```js
const NpmApi = require('npm-api');
const npm = new NpmApi();
```

That will get rid of the error that you have, but unfortunately, due to the changes that NPM made to their API, this package won't work in its current state. This package relied on NPM's couchdb views to get the dependents.

If I get a chance, this weekend, I'll take a look and see if I can update it to work again with `npm-api`.

**Comment by flotwig** [comment]
Ah, gotcha. Yeah, it seems like a lot of packages that claim do do this 1 thing no longer work. Is there documentation for their API somewhere?

**Comment by LinqLover** [comment]
I cannot get this working, too. When running the example, it says:

```js
const NpmApi = require('npm-api');
const npm = new NpmApi();

var dependents = require('npm-api-dependents');
npm.use(dependents());

var repo = npm.repo('micromatch');

// returns a readable stream
repo.dependents()
	.on('data', function (repo) {
		console.log(repo);
	});
```

```
TypeError: repo.dependents is not a function
```

Any chance to get this fixed soon? :-)

**Comment by doowb** [comment]
This module was created to work with versions of `npm-api` below `1.0.0`. As of version `1.0.0`, it was refactored and plugins work differently. I haven't had a chance to update `npm-api-dependents` to work with the new system yet mainly due to the changes that NPM did to their api.

To get the example working, you might be able to use `npm-api@0.4.13` or try the following with the latest:

```js
const NpmApi = require('npm-api');
const npm = new NpmApi();

const dependents = require('npm-api-dependents');

// try to trick the first "plugin" to work by adding `isNpmapi = true` to the `npm` instance
npm.isNpmapi = true;

// make sure to invoke the `dependents` function first, then use `.call` on the returned function to set the `this` context
const plugin = dependents().call(npm, npm);

const repo = npm.repo('micromatch');

// try to trick the second "plugin" to work by adding `isRepo = true` to the `repo` instance
repo.isRepo = true;

// pass the "repo plugin" directly to the `repo.use` method
repo.use(plugin);

// returns a readable stream
repo.dependents()
	.on('data', function (repo) {
		console.log(repo);
	});
```

I'll try to get around to updating this, but I'm open to reviewing PRs to get this module updated.
